# Basic Auth Middleware
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: "{{ .Release.Name }}-{{ .Chart.Name }}-auth"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: { ? { .Chart.AppVersion | quote } }
    app.kubernetes.io/component: { ? { .Values.component | default "application" | quote } }
    app.kubernetes.io/part-of: "{{ .Chart.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
spec:
  basicAuth:
    secret: "{{ .Release.Name }}-{{ .Chart.Name }}-auth"
    realm: "{{ .Chart.Name }} Access"
    removeHeader: true

# HTTPS Redirect Middleware
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: "{{ .Release.Name }}-{{ .Chart.Name }}-https-redirect"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: { ? { .Chart.AppVersion | quote } }
    app.kubernetes.io/component: { ? { .Values.component | default "application" | quote } }
    app.kubernetes.io/part-of: "{{ .Chart.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
spec:
  redirectScheme:
    scheme: https
    permanent: true

# CORS Headers Middleware  
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: "{{ .Release.Name }}-{{ .Chart.Name }}-cors"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: { ? { .Chart.AppVersion | quote } }
    app.kubernetes.io/component: { ? { .Values.component | default "application" | quote } }
    app.kubernetes.io/part-of: "{{ .Chart.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
spec:
  headers:
    accessControlAllowMethods:
    - GET
    - POST
    - PUT
    - DELETE
    accessControlAllowOriginList:
    - "*"
    customRequestHeaders:
      X-Forwarded-Proto: "https"

# PADRÕES:
# - Nome: {{ .Release.Name }}-{{ .Chart.Name }}-TIPO
# - Labels: Todas as 6 labels kubernetes.io
# - Tipos comuns: auth, https-redirect, cors, strip-prefix
# - Secret para auth: mesmo nome do middleware 
