apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-{{ .Chart.Name }}-data"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/component: {{ .Values.component | default "application" | quote }}
    app.kubernetes.io/part-of: "{{ .Chart.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.persistence.size | default \"1Gi\" }}"
  {{- if .Values.persistence.storageClass }}
  {{- if eq .Values.persistence.storageClass "-" }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
  {{- end }}
  {{- end }}

# PADRÕES:
# - Nome: {{ .Release.Name }}-{{ .Chart.Name }}-data
# - Labels: Todas as 6 labels kubernetes.io
# - AccessMode: ReadWriteOnce (padrão)
# - Size: Configurável via .Values.persistence.size
# - StorageClass: Opcional via .Values.persistence.storageClass 
