apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-{{ .Chart.Name }}-secret"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: { ? { .Chart.AppVersion | quote } }
    app.kubernetes.io/component: { ? { .Values.component | default "application" | quote } }
    app.kubernetes.io/part-of: "{{ .Chart.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
type: Opaque
data:
  # Valores são automaticamente codificados em base64
  username: "{{ .Values.database.username | b64enc }}"
  password: "{{ .Values.database.password | b64enc }}"
  api-key: "{{ .Values.api.key | b64enc }}"

# Para Basic Auth (Traefik):
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-{{ .Chart.Name }}-auth"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: { ? { .Chart.AppVersion | quote } }
    app.kubernetes.io/component: { ? { .Values.component | default "application" | quote } }
    app.kubernetes.io/part-of: "{{ .Chart.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
type: Opaque
data:
  users: "{{ htpasswd .Values.auth.username .Values.auth.password | b64enc }}"

# PADRÕES:
# - Nome: {{ .Release.Name }}-{{ .Chart.Name }}-secret
# - Labels: Todas as 6 labels kubernetes.io
# - Type: Opaque (padrão) ou kubernetes.io/tls
# - Use b64enc para codificar valores
# - Para auth: use htpasswd para criar hash 
