apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/component: {{ .Values.component | default "storage" }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  entryPoints:
  - web
  {{- if .Values.tls.enabled }}
  - websecure
  {{- end }}
  routes:
  - match: Host(`{{ .Values.domain }}`)
    kind: Rule
    services:
    - name: longhorn-frontend
      port: 80
    {{- if .Values.auth.enabled }}
    middlewares:
    - name: {{ .Release.Name }}-{{ .Chart.Name }}-auth
    {{- end }}
  {{- if .Values.tls.enabled }}
  tls:
    certResolver: letsencrypt
  {{- end }} 