{{- if and .Values.serviceAccount.create .Values.serviceAccount.createToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-sa-token
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/component: {{ .Values.component | default "application" | quote }}
    app.kubernetes.io/part-of: "{{ .Chart.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
  annotations:
    kubernetes.io/service-account.name: {{ .Release.Name }}-{{ .Chart.Name }}-sa
type: kubernetes.io/service-account-token
{{- end }} 