{{- if .Values.githubToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-github-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: github-actions
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  github_token: {{ .Values.githubToken | b64enc | quote }}
{{- end }} 