{{- if .Values.auth.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/component: {{ .Values.component | default "database" }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.auth.username | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.auth.password | b64enc | quote }}
  {{- if .Values.auth.database }}
  POSTGRES_DB: {{ .Values.auth.database | b64enc | quote }}
  {{- end }}
  PGDATA: {{ "/var/lib/postgresql/data/pgdata" | b64enc | quote }}
{{- end }} 