apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/component: {{ .Values.component | default "storage" }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{- $username := .Values.auth.username | default "admin" }}
  {{- $password := .Values.auth.password | required "auth.password é obrigatório para o MinIO" }}
  MINIO_ROOT_USER: {{ $username | b64enc | quote }}
  MINIO_ROOT_PASSWORD: {{ $password | b64enc | quote }} 