apiVersion: v2
name: actions-runners
description: GitHub Actions Runners para cluster k3s
type: application
version: 0.1.0
appVersion: "2.325.0"
keywords:
- github
- actions
- runners
- ci-cd
- k3s
home: https://github.com/m5o/k8s
sources:
- https://github.com/actions/actions-runner-controller
maintainers:
- name: m5o
  url: https://github.com/m5o
dependencies:
- name: gha-runner-scale-set
  version: "0.12.0"
  repository: "oci://ghcr.io/actions/actions-runner-controller-charts"
