apiVersion: v2
name: bridge
description: 🌉 Ponte que permite configurar kubeconfig via token (sem certificados), utilizando bitnami/kubectl internamente para facilitar acesso ao cluster
type: application
version: 1.0.0
appVersion: "latest"
keywords:
- kubernetes
- tutorial
- bridge
- kubeconfig
- proxy
home: https://github.com/m5o-tech/bridge
sources:
- https://github.com/m5o-tech/bridge
maintainers:
- name: M5O Team
  email: contato@m5o.dev
